# Define services
services:
  # App Service
  app:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:${APP_PORT}" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    
    depends_on:
      - redis 
      - mariadb
      - postgres
      - dbgate
    # volumes:
    #   - './:/app'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  mariadb:
    container_name: 'db'
    image: 'mariadb:10'
    restart: always
    
    env_file:
      - .env
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - '/docker_volume/mariadb:/var/lib/mysql'
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - /docker_volume/postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  
  #   restart: always
  #   depends_on:
  #     - postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5050:5050"
  #   volumes:
  #     - /docker_volume/pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - backend
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
        - mariadb
    environment:
        PMA_HOST: mariadb
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
        - "8081:80"
    networks:
        - backend

  dbgate:
    image: dbgate/dbgate
    container_name: dbgate
    
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /docker_volume/dbgate-data:/root/.dbgate
    networks:
        - backend


  # Redis Service
  redis:
    image: "redis:alpine" # Use a public Redis image to build the redis service
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - backend

networks:
  backend:
    driver: bridge